name: YDPortal
description: A simple portal plugin,changed from MTP
version: 1.3.2
author: aliuly&labi
main: YDPortal\Main
api: 1.0.0
load: POSTWORLD

commands:
  mtp:
    description: Create a portal
    usage: "/mtp [world] [x y z]"
    permission: mtp.cmd.mtp

permissions:
  mtp.cmd.mtp:
    default: op
    description: "Allow to create portal"
  mtp.destroy:
    default: op
    description: Allow destruction of portals
